---
# tasks file for testrole
- debug:
    msg: "hello {{ testvar }} !"
- template:
    src: test.conf.j2
    dest: /opt/test.conf
- debug:
    msg: "hello testrole!"
  changed_when: true
  notify: test_handler
